apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-background-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: lucasstark95/notification:latest
        ports:
        - containerPort: 8080