apiVersion: v1
kind: Service
metadata:
  name: person-dotnet-api-service
spec:
  selector:
    app: person-dotnet-api
  ports:
    - protocol: TCP
      port: 2195
      targetPort: 8080
  type: LoadBalancer