apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - protocol: TCP
    name: porta-primaria
    port: 5672
    targetPort: 5672
  - protocol: TCP
    name: porta-secundaria
    port: 15672
    targetPort: 15672
