apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_PASSWORD: pos12345
  POSTGRES_USER: postgres
  POSTGRES_DB: postech
  POSTGRES_ROOT_PASSWORD: root
  POSTGRES_HOST_AUTH_METHOD: "trust"
